/* eslint-disable @next/next/no-img-element */
import { JSX, SVGProps } from "react"

/***
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QwLraMAh82E
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function Landing() {
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      <header className="flex flex-col items-start bg-gray-800 p-4 md:flex-row md:items-center md:justify-between">
        <div className="flex items-center justify-between w-full mb-4 md:mb-0">
          <div className="text-3xl font-bold">rentagirlfriend</div>
          <button className="md:hidden">
            <MenuIcon className="h-6 w-6 text-white" />
          </button>
        </div>
        <nav className="flex flex-col space-y-4 md:flex-row md:space-y-0 md:space-x-4">
          <a href="#" className="text-white">
            Home
          </a>
          <a href="#" className="text-white">
            Blog
          </a>
          <a href="#" className="text-white">
            Login
          </a>
          <a href="#" className="text-white">
            Advertise on RG
          </a>
          <a href="#" className="text-white">
            Popular Locations
          </a>
          <a href="#" className="text-white">
            Live Cams
          </a>
        </nav>
      </header>
      <div className="flex flex-col items-center justify-between p-4 bg-gray-700 md:flex-row">
        <div className="flex flex-wrap justify-center gap-2 md:gap-4">
          <a href="#" className="text-white">
            Adelaide
          </a>
          <a href="#" className="text-white">
            Brisbane
          </a>
          <a href="#" className="text-white">
            Cairns
          </a>
          <a href="#" className="text-white">
            Canberra
          </a>
          <a href="#" className="text-white">
            Darwin
          </a>
          <a href="#" className="text-white">
            Gold Coast
          </a>
          <a href="#" className="text-white">
            Hobart
          </a>
          <a href="#" className="text-white">
            Melbourne
          </a>
          <a href="#" className="text-white">
            Newcastle
          </a>
          <a href="#" className="text-white">
            Perth
          </a>
          <a href="#" className="text-white">
            Sydney
          </a>
        </div>
        <form className="flex w-full mt-4 md:mt-0 md:w-auto">
          <input
            type="text"
            placeholder="Enter a location to find local escorts"
            className="p-2 bg-gray-600 text-white flex-1 md:w-auto"
          />
          <button className="p-2 bg-purple-600">Find Escorts</button>
        </form>
      </div>
      <main className="p-4">
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Latest Escorts from Australia</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {[...Array(6)].map((_, index) => (
              <div key={index} className="bg-gray-800 p-4">
                <img src="/placeholder.svg" alt="Escort" className="w-full h-48 object-cover mb-2" />
                <div className="text-center">
                  <h3 className="text-lg font-bold">Escort Name</h3>
                  <p>From $250</p>
                  <p>25y</p>
                </div>
              </div>
            ))}
          </div>
        </section>
        <section>
          <h2 className="text-2xl font-bold mb-4">Popular Escorts</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {[...Array(18)].map((_, index) => (
              <div key={index} className="bg-gray-800 p-4">
                <img src="/placeholder.svg" alt="Escort" className="w-full h-48 object-cover mb-2" />
                <div className="text-center">
                  <h3 className="text-lg font-bold">Escort Name</h3>
                  <p>From $250</p>
                  <p>25y</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  )
}

function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


export default Landing;